routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::resources(['categories' => 'CategoryController'],['names' => [
//    'edit' => 'categories.edit'
//]]
//);


Route::resource('categories', 'CategoryController');
Route::resource('articles', 'ArticleController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'category_id',
        'title',
        'author',
        'slug',
        'description',
        'content',
        'is_active'
    ];

    protected $casts = [
        'title' => 'string'
    ];

    public function categories()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
//use App\Repositories\Contracts\ArticleRepositoryInterFace;
use App\Http\Requests\ArticleRequest;
use App\Http\Resources\ArticleResource;
use App\Repositories\Eloquents\ArticleRepository;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $articleRepository;


    public function __construct(ArticleRepository $articleRepository)
    {
        $this->articleRepository = $articleRepository;
    }

    public function index()
    {
        $articles = $this->articleRepository->index();

        return view('admin.article.index',compact('articles'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.article.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $flag =  $this->articleRepository->store($request);

        if ($flag) {
            session()->flash('success', "Success!!!");
        } else {
            session()->flash('danger', "Fail!!!");
        }

        return redirect(route('articles.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return $articles = new ArticleResource(Article::findOrFail($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article =  $this->articleRepository->edit($id);

        return view('admin.article.edit',compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, $id)
    {
        $flag = $this->articleRepository->update($request,$id);

        if ($flag) {
            session()->flash('success', "Success!!");
        } else {
            session()->flash('danger', "Fail!!!");
        }

        return redirect()->route('articles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $msg = $this->articleRepository->destroy($id);

        if ($msg) {
            return response()->json(array(
                'status' => 204,
                'msg' => '204: HTTP requests successful'
            ));
        }
        return response()->json(array(
            'status' => 400,
            'msg' => '400: Bad Request'
        ));
    }
}

resources/views/admin/article/create.blade.php
@extends('layouts.app-admin')

@section('content')
    <section class="content-header">
        <h1>
            Category
            {{--<small>advanced tables</small>--}}
        </h1>
        {{--<ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>--}}
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">
                            {{--<small>Advanced and full of features</small>--}}
                        </h3>
                        <!-- tools box -->
                        <div class="pull-right box-tools">
                            <button type="button" class="btn btn-info btn-sm" data-widget="collapse"
                                    data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip"
                                    title="Remove">
                                <i class="fa fa-times"></i></button>

                        </div>
                        <!-- /. tools -->
                    </div>
                    <!-- /.box-header -->

                    <div class="box-body pad">
                        <form action="{{ route('articles.store') }}" method="post">
                            @csrf
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="code">Title:</label>
                                    <input type="text" name="title" id="title" class="form-control" onkeyup="generateSlug('title','slug')">
                                    @if ($errors->has('title'))
                                        <div class=" text-danger">
                                            {{  $errors->first('title') }}
                                        </div>
                                    @endif
                                </div>

                                <!-- Date range -->

                                <!-- /.form group -->
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="code">Slug:</label>
                                    <input type="text" class="form-control" name="slug" id="slug">
                                    @if ($errors->has('slug'))
                                        <div class=" text-danger">
                                            {{  $errors->first('slug') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Description:</label>
                                    <input type="text" name="description" class="form-control pull-right">
                                    @if ($errors->has('description'))
                                        <div class=" text-danger">
                                            {{  $errors->first('description') }}
                                        </div>
                                @endif
                                <!-- /.input group -->
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Author:</label>
                                    <input type="text" name="author" class="form-control pull-right">
                                    @if ($errors->has('author'))
                                        <div class=" text-danger">
                                            {{  $errors->first('author') }}
                                        </div>
                                @endif
                                <!-- /.input group -->
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="editor">Content</label>
                                    <textarea id="editor" name="content" rows="10" class="form-control"></textarea>
                                    @if ($errors->has('content'))
                                        <div class=" text-danger">
                                            {{  $errors->first('content') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="box-footer text-center ">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <a href="{{ asset('articles') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection

@section('js')

    {{--editor--}}
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>
    <script>
        $(function () {
            CKEDITOR.replace('editor'); // ID Tag
        })
    </script>
    <script>
        function generateSlug(inputStart, inputEnd) {
            var title;
            var slug;

            //Lấy text từ thẻ input title
            title = document.getElementById(inputStart).value;

            //Đổi chữ hoa thành chữ thường
            slug = title.toLowerCase();

            //Đổi ký tự có dấu thành không dấu
            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
            slug = slug.replace(/đ/gi, 'd');
            //Xóa các ký tự đặt biệt
            slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*||∣|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
            //Đổi khoảng trắng thành ký tự gạch ngang
            slug = slug.replace(/ /gi, "-");
            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
            slug = slug.replace(/\-\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-/gi, '-');
            slug = slug.replace(/\-\-/gi, '-');
            //Xóa các ký tự gạch ngang ở đầu và cuối
            slug = '@' + slug + '@';
            slug = slug.replace(/\@\-|\-\@|\@/gi, '') + '.html';
            //In slug ra textbox có id “slug”
            document.getElementById(inputEnd).value = slug;
        }
    </script>
@endsection

resources/views/admin/article/edit.blade.php
@extends('layouts.app-admin')

@section('content')
    <section class="content-header">
        <h1>
            Category
            {{--<small>advanced tables</small>--}}
        </h1>
        {{--<ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>--}}
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box box-info">
                    <div class="box-header">
                        <h3 class="box-title">
                            {{--<small>Advanced and full of features</small>--}}
                        </h3>
                        <!-- tools box -->
                        <div class="pull-right box-tools">
                            <button type="button" class="btn btn-info btn-sm" data-widget="collapse"
                                    data-toggle="tooltip"
                                    title="Collapse">
                                <i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip"
                                    title="Remove">
                                <i class="fa fa-times"></i></button>

                        </div>
                        <!-- /. tools -->
                    </div>
                    <!-- /.box-header -->

                    <div class="box-body pad">
                        <form action="{{ route('articles.update',$article['id']) }}" method="post">
                            @method('PUT')
                            @csrf
                            <input type="hidden" name="id" value="{{ $article['id'] }}">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="code">Name:</label>
                                    <input type="text" name="title" value="{{ $article['title'] }}" id="title" class="form-control" onkeyup="generateSlug('title','slug')">
                                    @if ($errors->has('title'))
                                        <div class=" text-danger">
                                            {{  $errors->first('title') }}
                                        </div>
                                    @endif
                                </div>

                                <!-- Date range -->

                                <!-- /.form group -->
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="code">Slug:</label>
                                    <input type="text" class="form-control" value="{{ $article['slug'] }}" name="slug" id="slug">
                                    @if ($errors->has('slug'))
                                        <div class=" text-danger">
                                            {{  $errors->first('slug') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="code">Author:</label>
                                    <input type="text" class="form-control" value="{{ $article['author'] }}" name="author" id="author">
                                    @if ($errors->has('author'))
                                        <div class=" text-danger">
                                            {{  $errors->first('author') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Description:</label>
                                    <input type="text" name="description" value="{{ $article['description'] }}" class="form-control pull-right">
                                    @if ($errors->has('description'))
                                        <div class=" text-danger">
                                            {{  $errors->first('description') }}
                                        </div>
                                @endif
                                <!-- /.input group -->
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="editor">Content</label>
                                    <textarea id="editor" name="content" rows="10" class="form-control">{{ $article['content'] }}</textarea>
                                    @if ($errors->has('content'))
                                        <div class=" text-danger">
                                            {{  $errors->first('content') }}
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="box-footer text-center ">
                                <button type="submit" class="btn btn-success">Submit</button>
                                <a href="{{ route('articles.index') }}" class="btn btn-danger">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection

@section('js')

    {{--editor--}}
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>
    <script>
        $(function () {
            CKEDITOR.replace('editor'); // ID Tag
        })
    </script>
    <script>
        function generateSlug(inputStart, inputEnd) {
            var title;
            var slug;

            //Lấy text từ thẻ input title
            title = document.getElementById(inputStart).value;

            //Đổi chữ hoa thành chữ thường
            slug = title.toLowerCase();

            //Đổi ký tự có dấu thành không dấu
            slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
            slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
            slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
            slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
            slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
            slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
            slug = slug.replace(/đ/gi, 'd');
            //Xóa các ký tự đặt biệt
            slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*||∣|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
            //Đổi khoảng trắng thành ký tự gạch ngang
            slug = slug.replace(/ /gi, "-");
            //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
            //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
            slug = slug.replace(/\-\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-\-/gi, '-');
            slug = slug.replace(/\-\-\-/gi, '-');
            slug = slug.replace(/\-\-/gi, '-');
            //Xóa các ký tự gạch ngang ở đầu và cuối
            slug = '@' + slug + '@';
            slug = slug.replace(/\@\-|\-\@|\@/gi, '') + '.html';
            //In slug ra textbox có id “slug”
            document.getElementById(inputEnd).value = slug;
        }
    </script>
@endsection

resources/views/admin/article/index.blade.php
@extends('layouts.app-admin')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
           Article
            {{--<small>advanced tables</small>--}}
        </h1>
        {{--<ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">eateData tables</li>
        </ol>--}}
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <a href="{{ route('articles.create') }}"><button class="btn btn-success">Add <i class="fa fa-plus"></i></button></a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="datatables" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th>STT</th>
                                <th>Title </th>
                                <th>Author</th>
                                <th>Content </th>
                                <th>Action  </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($articles as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item['title'] }}</td>
                                    <td>{{ $item['author'] }}</td>
                                    <td>{!! $item['content'] !!}</td>
                                    <td>
                                        <a href="{{ route('articles.edit',$item['id']) }}" class="btn btn-xs btn-info" title=""><i class="fa fa-edit"></i></a>
                                        <a href="{{ route('articles.destroy',$item['id']) }}" class=" destroy btn btn-xs btn-danger" title=""><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection
@section('js')
    <script src="admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <script>
        $(function () {
            $('#datatables').DataTable({
                'paging'      : true,
                'lengthChange': true,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : true
            })
        })
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script>
        $('.destroy').click(function (e) {
            e.preventDefault();
            var _this = this;
            var url = $(this).attr('href');

            bootbox.confirm({
                title: "Destroy?",
                message: "Are you sure?",
                buttons: {
                    cancel: {
                        label: '<i class="fa fa-times"></i> Cancel'
                    },
                    confirm: {
                        label: '<i class="fa fa-check"></i> Confirm'
                    }
                },
                callback: function (result) {
                    if (result) {
                        $.ajax({
                            url: url,
                            type: 'delete',
                            dataType: 'json',
                            success: function (rs) {
                                if (rs.status === 204) {
                                    $(_this).parents().eq(1).remove();
                                    bootbox.alert("Destroy success!");
                                } else {
                                    bootbox.alert("Destroy not success!");
                                }
                            },
                            error: function(XMLHttpRequest, textStatus, errorThrown) {
                                alert("Status: " + textStatus); alert("Error: " + errorThrown);
                            }
                        })
                    }
                }
            });
        })
    </script>
@endsection